name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the short commit hash
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: "Authenticate Cloud SDK"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-gemini-test:${{ env.short_sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-gemini-test:${{ env.short_sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gcp-gemini-test \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-gemini-test:${{ env.short_sha }} \
            --tag gcp-gemini-test-${{ env.short_sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --update-env-vars GCP_LOCATION=${{ secrets.GCP_LOCATION }} \
            --update-env-vars GCP_PROCESSOR_ID=${{ secrets.GCP_PROCESSOR_ID }}